### ISSUE TITLE
Integrating Onvif (ie Home Assistant) 

### ISSUE THREAD

**Issue by BytheWWW** [guino/BazzDoorbell#8]

**Comment by BytheWWW** [comment]
@lesleyvanrijn Did your home assistant find the doorbell automatically?

**Comment by lesleyvanrijn** [comment]
@BytheWWW Yep, with this settings:

Name: Whatever you fancy
Host: IP of the device
Port: 8000
User: admin
Passw: admin

After that it will add the camera to your home assistant instance. After that you'll have to update the connection type to TCP.

**Comment by BytheWWW** [comment]
@lesleyvanrijn Was trying to connect through port 8554 🤪

It's visible in HA now. Now the main reason for me to integrate it into HA was to be able to hear a chime through Google home when someone was ringing the doorbell

**Comment by lesleyvanrijn** [comment]
@BytheWWW That is possible! 

1: Add the  [MQTT middleware](https://github.com/guino/BazzDoorbell/issues/4#issuecomment-740644879) to the doorbell (at the end of that reply is a zip and instructions for adding the middleware). 
2: Create a MQTT server in Home Assistant, follow steps 1-6 of [this tutorial](https://medium.com/@fedorets.alex/hass-io-zigbee2mqtt-io-the-simplest-way-b7375c9fba22)
3: Update configuration.yaml and add:
```
mqtt:
  broker: 127.0.0.1
```
4: Create a new automation:
````
**Trigger:**
platform: mqtt
    topic: home/doorbell/button
    payload: pushed

**Actions:**
  - service: mqtt.publish
    data:
      topic: home/doorbell/button
      payload: idle
  
  - service: camera.play_stream
    data:
      entity_id: camera.{id} << ADD ID
      media_player: media_player.{id} << ADD ID
  
````
